import io
import glob
import logging
import os
from pathlib import Path
import sys
import tarfile

import numpy as np
import webdataset as wds
import wids
from tqdm import tqdm

from ...dataloader.utils import md5
from .feature_store import FeatureStore

logger = logging.getLogger()
class WebdatasetStore(FeatureStore):
    def __init__(self, store_name, store_data_dir):
        """
        Store all data in the specified directory as numpy .npy binary file

        Parameters
        ----------
        store_name : string
            a string prefix that gets added to all files generated by this store
        store_data_dir : string
            all assets of this store are saved in this folder
        shard_maxcount : int
            maximum number of records per shard
        shard_maxsize : int
            maximum size of each shard

        References:
        [1] https://github.com/webdataset/webdataset/blob/main/examples/wds-notes.ipynb
        [2] https://webdataset.github.io/webdataset/api/webdataset/writer.html
        """
        self.store_name = store_name
        self.store_data_dir = store_data_dir
        self.EXTENSION = 'tar'
        self.store_data_filename = os.path.join(self.store_data_dir,
                                                self.store_name + '-%06d.' + self.EXTENSION)
        self._wds_tar_prefix = os.path.join(self.store_data_dir, self.store_name + '-')

        self.shard_list_dataset = None
        self.vector_id_to_webdataset_idx_mapping = None
        self._tar_filenames = []

        # key: filesize of tar file; value: number of features in tar file
        self._filesize_to_count_mapping = {}

        self._reset()
        self.enable_read()

    def _reset(self):
        self._tar_filenames = self._get_current_tar_filenames()
        self.shard_list_dataset = None
        self.vector_id_to_webdataset_idx_mapping = None

    @property
    def tar_filenames(self):
        return self._tar_filenames

    def _get_current_tar_filenames(self):
        wds_tar_pattern = self._wds_tar_prefix + '*.tar'
        return sorted(glob.iglob(pathname=wds_tar_pattern, recursive=False))

    def _update_tar_filenames(self, fname):
        self._tar_filenames.append(fname)

    @property
    def feature_count(self):
        # Fast method for counting the total number of features
        # We assume that tar files with the same filesize have the same number of features.
        # The process of counting the number of files (features) within a tar is slow,
        # whereas filesizes can be computed much faster.
        # Therefore, after we have counted the number of features of a given tar file,
        # we skip the counting process for all the other tar files with the same filesize
        _feature_count = 0
        for tar_filename in self.tar_filenames:
            filesize = os.stat(tar_filename).st_size
            if filesize not in self._filesize_to_count_mapping:
                with tarfile.open(tar_filename) as f:
                    # Count the number of files in the tar (assuming each file is a feature vector)
                    self._filesize_to_count_mapping[filesize] = sum(1 for member in f if member.isreg())
            _feature_count += self._filesize_to_count_mapping[filesize]

        return _feature_count

    @property
    def wds_src_url(self):
        if len(self.tar_filenames) == 0:
            raise ValueError(f'No webdataset tar files matching {self._wds_tar_prefix}*.tar found!')

        # Load the feature dimension
        tar_index = [sys.maxsize, -1]
        tar_index_str = ['', '']
        for tar_filename in self.tar_filenames:
            tar_filename_tok = tar_filename.split(self._wds_tar_prefix)
            _tar_index = tar_filename_tok[1].split('.tar')[0]
            if int(_tar_index) < tar_index[0]:
                tar_index[0] = int(_tar_index)
                tar_index_str[0] = _tar_index
            if int(_tar_index) > tar_index[1]:
                tar_index[1] = int(_tar_index)
                tar_index_str[1] = _tar_index
        tar_index_range = '{%s..%s}' % (tar_index_str[0], tar_index_str[1])
        return self._wds_tar_prefix + tar_index_range + '.tar'

    @property
    def feature_dim(self) -> int | None:
        if len(self.tar_filenames) == 0:
            return None

        with wds.WebDataset(self.wds_src_url,
                                           shardshuffle=False,
                                           repeat=False) as temp_shard_reader:
            for payload in temp_shard_reader:
                feature_vector = np.load(io.BytesIO(payload['features.pyd']), allow_pickle=True)
                return feature_vector.shape[1]

    def enable_write(self, shard_maxcount = 100_000, shard_maxsize = 3 * 1024 ** 3, verbose=0, overwrite: bool = False):
        self.shard_maxcount = shard_maxcount
        self.shard_maxsize = shard_maxsize
        if overwrite:
            for tar_filename in self.tar_filenames:
                Path(tar_filename).unlink(missing_ok=True)
            self._reset()

        self.shardWriter = wds.ShardWriter(
            pattern=self.store_data_filename,
            maxcount=self.shard_maxcount,
            maxsize=self.shard_maxsize,
            verbose=verbose,
            start_shard=len(self.tar_filenames),
            post=self._update_tar_filenames,
        )

    def enable_read(self, shard_shuffle=False, shuffle_values=False, shuffle_bufsize=10000):
        self.shard_shuffle = shard_shuffle
        self.shuffle_values = shuffle_values
        self.shuffle_bufsize = shuffle_bufsize if self.shuffle_values else -1

    def add(self, id, features):
        if not self.shardWriter:
            raise ValueError('enable_write() must be activated before invoking add() method')
        self.shardWriter.write({
            '__key__': ('%010d' % id), # needs to be a string
            'features.pyd': features
        })

    def _webdataset(self):
        def numpy_decoder(key, value):
            assert key.endswith('features.pyd'), f"Unexpected key: {key}"
            assert isinstance(value, bytes), f"Unexpected type: {type(value)}"
            return np.load(io.BytesIO(value), allow_pickle=True)

        return (
            wds.WebDataset(
                self.wds_src_url,
                shardshuffle=self.shard_shuffle,
                repeat=False
            )
            .shuffle(self.shuffle_bufsize)
            .decode(numpy_decoder)
            .to_tuple("__key__", "features.pyd")
            .map_tuple(
                int,
                lambda x: x
            )
        )

    def __iter__(self):
        with self._webdataset() as wds:
            yield from wds

    def iter_batch(self, batch_size=512):
        with (
            self._webdataset()
            .map_tuple(
                lambda x: x, # convert key to int
                lambda x: x.squeeze(axis=0), # change shape of numpy array from (1, d) to (d,)
            )
            .batched(batch_size)
        ) as _wds:
            yield from _wds

    def enable_random_access(self):
        """
        Enables random access to the WebDataset store for the internal search feature.
        Once enabled, feature vectors can be accessed directly using their vector id.

        Usage example:
        ```
        store = WebdatasetStore(...)
        store.enable_read()
        store.enable_random_access()
        
        # Access a feature vector with an id of 123
        vector = store[123]
        ```

        Internally, these two things are created:
        1. A list of 'shards', in the same format as the 'shardlist' array in this
            example: https://storage.googleapis.com/webdataset/fake-imagenet/imagenet-train.json

            This is used to initialize a wids.ShardListDataset instance which is saved to
            self.shard_list_dataset. The wids.ShardListDataset instance is what provides
            random access to the feature vectors.

        2. A mapping between the vector ids and indices used to access the ShardListDataset.

            This is needed because the index of a vector within the ShardListDataset is different
            from its vector id. For example, shard_list_dataset[0] might have a vector id of 1 
            (instead of 0), and shard_list_dataset[8] might have a vector id of 11

        """

        shardlist = []
        # a dictionary with key: vector id and value: webdataset index
        vector_id_to_webdataset_idx_mapping: dict[int, int] = {}
        webdataset_idx = 0
        logger.info("Enabling random access to feature store")
        for tar_filename in tqdm(self.tar_filenames):
            nsamples = None
            with tarfile.open(tar_filename) as f:
                feature_filenames = f.getnames()
                nsamples = len(feature_filenames)
                for feature_filename in feature_filenames:
                    # Get the vector id from each filename, e.g. 123456 from '0000123456.features.pyd'
                    vector_id = int(feature_filename.split('.')[0])
                    vector_id_to_webdataset_idx_mapping[vector_id] = webdataset_idx
                    webdataset_idx += 1

            shardlist.append({
                "url": tar_filename,
                "md5sum": md5(tar_filename),
                "nsamples": nsamples,
                "filesize": os.stat(tar_filename).st_size,
            })
        self.shard_list_dataset = wids.ShardListDataset(shardlist)
        self.vector_id_to_webdataset_idx_mapping = vector_id_to_webdataset_idx_mapping
        # Note: in the future, we could save the shardlist and vector_id_to_webdataset_idx_mapping
        # as JSON files to disk, so that they do not need to be re-computed each time
        # we want to enable random access.
        # The md5 checksums in the shardlist can be used to detect whether the feature store
        # has been modified (to determine whether the shardlist and id mapping need to be
        # re-computed)

    def __getitem__(self, vector_id: int) -> np.ndarray:
        """
        Access a feature vector with its vector id. The `enable_random_access()`
        method needs to be called first in order to enable this.

        Usage example:
        ```
        store = WebdatasetStore(...)
        store.enable_read()
        store.enable_random_access()
        
        # Access a feature vector with an id of 123
        vector = store[123]
        ```
        """
        if not self.shard_list_dataset or not self.vector_id_to_webdataset_idx_mapping:
            raise Exception("Please run `store.enable_random_access()` on this feature store first")
        webdataset_idx = self.vector_id_to_webdataset_idx_mapping[vector_id]
        payload = self.shard_list_dataset[webdataset_idx]
        feature_vector = np.load(payload['.features.pyd'], allow_pickle=True)
        return feature_vector

    def close(self):
        if hasattr(self, "shardWriter") and hasattr(self.shardWriter, "tarstream"):
            self.shardWriter.close()

    def __del__(self):
        self.close()
