---
services:
  wise:
    image: ${REGISTRY:-$USER}/wise-cpu:${VERSION:-latest}
    build:
      args:
        - APP=wise-cpu

    # Set device ids to expose GPU to container
    deploy: !reset {}
    shm_size: !reset '64mb'