services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.06-py3
    command: tritonserver --model-repository=/models
    ports:
      - "8800:8000"  # HTTP
      - "8801:8001"  # gRPC
      - "8802:8002"  # Metrics

    environment:
      HF_HOME: "/cache/"
      PYTHONPATH: "/workspace/wise/src/:"

    volumes:
      - ./triton/models:/models
      - ./triton/cache:/cache
      - ./src/:/workspace/wise/src/
      - ./triton/wise-env:/wise-env

    shm_size: 2g
    ulimits:
      memlock: -1
      stack: 67108864

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: unless-stopped

