name: wise

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip=24
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - faiss-gpu=1.8.0
  - mkl=2023
  - blas=*=mkl
  - conda-forge::ffmpeg
  - pip:
    - -r requirements.txt
    # Install msclap separately till we pip freeze
    # pip install --no-deps msclap==1.3.3
variables:
  PYTHONNOUSERSITE: 1
