name: wise

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip=23
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - faiss-gpu=1.7.4
  - mkl=2021
  - blas=1.0=mkl
  - conda-forge::ffmpeg
  - pip:
      - -r requirements.txt

variables:
  PYTHONNOUSERSITE: 1
