channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults  # ensure default channel is not used due to its ToS

dependencies:
  - python=3.10
  - pip=24
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - faiss-gpu=1.8.0
  - python-magic=0.4
  - mkl=2023
  - blas=*=mkl
  - conda-forge::ffmpeg<7
  - pip:
    - -r requirements.txt
variables:
  PYTHONNOUSERSITE: 1
