services:
  wise:
    build:
      context: ../../
      dockerfile: scripts/cinephile/Dockerfile
      target: wise
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    image: wise:latest
    # Keep the container running in the background
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ENV_NAME=wise-env # default micromamba environment
    # HOST_UID and HOST_GID are needed at runtime to make sure the volume mounts work alright
    user: ${HOST_UID?'HOST_UID must be set before using this compose.yaml. Please see docs/Docker.md'}:${HOST_GID?'HOST_GID must be set before using this compose.yaml. Please see docs/Docker.md'}

    # Increase shared memory size to prevent segmentation faults with PyTorch/multiprocessing
    shm_size: '2gb'
    volumes:
      # For development: Mount the entire project directory to instantly reflect
      # local changes in the container. Remove for production.
      - ../../:/wise
      # Set the CINEPHILE_DATA_DIR environment variable on your host to map a local folder here.
      # For example: export CINEPHILE_DATA_DIR=/path/to/my/data
      - ${CINEPHILE_DATA_DIR}:/data/cinephile/

    ports:
      # Set the WISE_HOST_PORT environment variable to map a different host port.
      # Example: export WISE_HOST_PORT=12345
      - "${WISE_HOST_PORT:-10001}:10001"

  shot-detection:
    build:
      context: ../../
      dockerfile: scripts/cinephile/Dockerfile
      target: shot-detection-env
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    image: wise-shot-detection:latest
    # Keep the container running in the background
    tty: true
    environment:
      - ENV_NAME=shot-detection-env # default micromamba environment
    volumes:
      # Set the CINEPHILE_DATA_DIR environment variable on your host to map a local folder here.
      # For example: export CINEPHILE_DATA_DIR=/path/to/my/data
      - ${CINEPHILE_DATA_DIR}:/data/cinephile/

  shot-scale-classifier:
    build:
      context: ../../
      dockerfile: scripts/cinephile/Dockerfile
      target: shot-scale-classifier-env
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    image: wise-shot-scale-classifier:latest
    # Keep the container running in the background
    tty: true
    environment:
      - ENV_NAME=shot-scale-classifier-env # default micromamba environment
    volumes:
      # Set the CINEPHILE_DATA_DIR environment variable on your host to map a local folder here.
      # For example: export CINEPHILE_DATA_DIR=/path/to/my/data
      - ${CINEPHILE_DATA_DIR}:/data/cinephile/
