"""Add type column

Revision ID: 8075207cc5a4
Revises: 2d74f31f0c60
Create Date: 2023-02-28 02:25:01.763543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8075207cc5a4"
down_revision = "2d74f31f0c60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column(
            "type",
            sa.Enum("IMAGE_DIR", "WEBDATASET", name="datasettype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "type")
    # ### end Alembic commands ###
