"""Create Projects Table

Revision ID: 2336e1b7e3b1
Revises:
Create Date: 2023-02-28 00:06:58.886794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2336e1b7e3b1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Unicode(256), primary_key=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects")
    # ### end Alembic commands ###
