site_name: WISE Docs
site_url: https://www.robots.ox.ac.uk/~vgg/software/wise/
repo_name: vgg/wise/wise
repo_url: https://gitlab.com/vgg/wise/wise
docs_dir: src
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow

extra:
  repo_blob_infix: "/-/blob"   # GitLab; use "/blob" for GitHub

plugins:
  - search
  - autorefs
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            extensions:
              - griffe_typingdoc
            docstring_style: google
            docstring_section_style: table
            filters:
              - '!^_'
            merge_init_into_class: true
            show_if_no_docstring: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            unwrap_annotated: true
            show_docstring_type_parameters: true
            members_order: source

nav:
  - WISE: README.md
  - Install: docs/Install.md
  - User Guide:
    - docs/UserGuide.md
    - docs/Processing-Large-Datasets.md
  - Developer Resources:
      - docs/Development.md
      - docs/Database.md
      - docs/Docker.md
      - docs/Experimental.md
      - docs/data-loading.md
      - docs/FeatureExtractor.md
      - docs/FeatureStore.md
      - docs/Metadata.md
      - docs/Evaluation.md
      - Frontend: frontend/README.md
      - docs/Grammar-of-Audiovisual-Search.md
      - docs/Search-Index-Evaluation.md
      - docs/SearchIndex.md
      - docs/Shot-Detection.md
      - docs/Tests.md
      - docs/Thumbnails.md
      - docs/using-triton-inference-server.md
      - docs/WiseProject.md
  - API Reference:
      - docs/reference/wiseproject.md
      - docs/reference/datamodels.md
      - docs/reference/dataloading.md
      - docs/reference/repository.md
      - docs/reference/datatables.md
      - docs/reference/featurestore.md
      - docs/reference/searchindex.md
